config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, controllers: { sessions: 'users/sessions' }

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

  resources :charges, only: [:new, :create]

  root 'welcome#index'

  get 'downgrade' => 'downgrade'

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  def owner
    user
  end

  def possible_collaborators
    User.all.reject{ |u| u.id == user.id || users.include?(u) }
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  before_action :require_sign_in, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show, :new, :edit, :create, :update]
  def index
    @wikis = policy_scope(Wiki)
  end

  def new
    @wiki = Wiki.new
    @all_users = User.all
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.user= current_user
    @wiki.private = params[:wiki][:private]
    # @wiki.collaborator = Collaborator.new(wiki_id: @wiki, user_id: User.where(email: params[:new_collaborator]))

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the Wiki. Please try again."
      render :new
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    # @wiki.collaborator = Collaborator.new(wiki_id: @wiki, user_id: User.where(email: params[:new_collaborator]))
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the Wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully"
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the Wiki."
      render :show
    end
  end

  private

  def authorize_user
     unless current_user.admin?
       flash[:alert] = "You must be an admin to do that."
       redirect_to wikis_path
     end
   end

   def collaborator
     @wiki = Wiki.find(params[:id])
     @collaborator = Collaborator.new(wiki_id: @wiki, user_id: User.where(email: params[:new_collaborator]))
     @collaborator.save
   end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
  <%= form_for @wiki do |f| %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Edit your Wiki:</p>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
      </div>
      <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private wiki
        <% end %>
      <% end %>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>

    <%= link_to "Add Collaborators", new_wiki_collaborator_path(@wiki), class: 'btn btn-success' %>

app/views/wikis/index.html.erb
<div class="container">
  <h1>All Wikis</h1>
  <h5><%= link_to "New Wiki", new_wiki_path, class: "btn btn-success" %></h5>
</div>

<h2>Wikis:</h2>
<% @wikis.each do |wiki| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to wiki.title, wiki_path(wiki.id) %>
        </h4>
      </div>
    </div>
  <% end %>

  <% if (current_user && current_user.standard?) %>
      <h5>Upgrade to premium to make private Wikis! <%= link_to "Upgrade", new_charge_path, class: 'btn btn-success' %> </h5>
  <% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Please create your new Wiki:</p>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
      <%= render partial: 'form' %>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="rows">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <% if current_user %>
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% end %>
    <% if current_user && current_user.admin? %>
      <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this Wiki?"} %>
    <% end %>
  </div>
</div>

<div class="rows">
  <div class="col-md-8">
    Collaborators:
    <% @wiki.collaborators.each do |collaborator| %>
      <li> <%= collaborator.user.email %> <%= link_to 'X', wiki_collaborator_path(@wiki.id, collaborator.id), data: {confirm: 'Are you sure you want to remove this collaborator?'}, method: :delete %> </li>
    <% end %>
  </div>
</div>
<%= link_to "Add Collaborators", new_wiki_collaborator_path(@wiki), class: 'btn btn-success' %>