config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, controllers: { sessions: 'users/sessions' }

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

  resources :charges, only: [:new, :create]

  root 'welcome#index'

  get 'downgrade' => 'downgrade'

end

app/models/charge.rb
class Charge < ApplicationRecord
  # after_create :upgrade_to_premium
  #
  # def upgrade_to_premium
  #   current_user.update_attributes!(role: 'premium')
  # end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  # after_initialize { current_user.role = :premium }
  def create
   # Creates a Stripe Customer object, for associating
   # with the charge
   @amount = 1500

   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )

   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: @amount,
     description: "Premium Membership - #{current_user.email}",
     currency: 'usd'
   )

   upgrade(current_user)
  #  current_user.update_attributes!(role: 'premium')
   flash[:notice] = "Congratulations on updrading to a premium membership, #{current_user.email}!"
   redirect_to wikis_path # or wherever

   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
 end

 def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Premium Membership",
     amount: 1500
   }
 end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/new.html.erb
  <div class="container">
    <%= form_tag charges_path do %>
       <h2>Want to upgrade to premium?</h2>
       <h4>Just a one-time fee of $15.00!</h4>
       <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-image="https://stripe.com/img/documentation/checkout/marketplace.png" data-key="pk_test_5LgLqGMS3y1qb6Bqjnj1wond" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" data-email="<%= current_user.email %>"></script>
     <% end %>
  </div>